config/routes.rb
Rails.application.routes.draw do
  root 'messages#new'

  devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => "users/sessions", :passwords => "users/passwords", :confirmations => "users/confirmations"}

  get 'message' => 'messages#new', as: :message
  get '/customer/message' => 'customer_messages#new', as: :customer_message
  post '/message/send' => 'messages#send_message', as: :send_message
  post '/customer/message/send' => 'customer_messages#send_message', as: :customer_send_message
  get '/message/send' => 'messages#new'
  get '/customer/message/send' => 'customer_messages#new'
  get '/ad7e2b2a24677ed2eecf953edf1abfa1/b19e8e47-19f5-4162-8447-e56cb5ef8a34/api/message/:sender/:msisdn/:message' => 'messages#filter_api_send_message', :constraints => {:message => /[^\/]+/}
  get '/ad7e2b2a24677ed2eecf953edf1abfa1/b19e8e47-19f5-4162-8447-e56cb5ef8a34/api/message/:login/:password/:service_id/:sender/:msisdn/:message' => 'messages#filter_api_send_message', :constraints => {:message => /[^\/]+/}
  get '/ad7e2b2a24677ed2eecf953edf1abfa1/b19e8e47-19f5-4162-8447-e56cb5ef8a34/api/message/:msisdn/:message' => 'messages#api_send_message', :constraints => {:message => /[^\/]+/}
  get '/7720134caec8126d432ea3f2a011cc8f/bulk/:login' => 'messages#api_bulk'

  get "/md5_encrypt/:password/:service_id" => 'messages#api_md5_encrypt'

  get 'transactions' => 'transactions#list', as: :transactions
  get 'transactions/email' => 'email_transactions#list', as: :email_transactions
  get 'customer/transactions/email' => 'customer_email_transactions#list', as: :customer_email_transactions
  get 'customer/transactions' => 'customer_transactions#list', as: :customer_transactions

  get 'message_logs/:transaction_id' => 'message_logs#list', as: :message_logs
  get 'message_logs/export/:transaction_id' => 'message_logs#export', as: :export_message_logs
  get 'customer/message_logs/:transaction_id' => 'customer_message_logs#list', as: :customer_message_logs
  get 'customer/message_logs/export/:transaction_id' => 'customer_message_logs#export', as: :export_customer_message_logs

  get 'email_logs/:transaction_id' => 'email_logs#list', as: :email_logs
  get 'email_logs/export/:transaction_id' => 'email_logs#export', as: :export_email_logs
  get 'customer/email_logs/:transaction_id' => 'customer_email_logs#list', as: :customer_email_logs
  get 'customer/email_logs/export/:transaction_id' => 'customer/email_logs#export', as: :customer_export_email_logs

  get 'search' => 'search#index', as: :search
  get 'customer/search' => 'customer_search#index', as: :customer_search
  post 'search/perform' => 'search#perform', as: :perform_search
  post 'customer/search/perform' => 'customer_search#perform', as: :customer_perform_search
  get 'search/perform' => 'search#index'
  get 'customer/search/perform' => 'customer_search#index'

  get "request_log" => "custom_logs#logs"

  get "/customer/new" => "customers#new", as: :new_customer
  post "/customer/create" => "customers#create", as: :create_customer
  get "/customer/create" => "customers#new"
  get "/customers/list" => "customers#list", as: :list_customers
  get "/customer/edit/:customer_id" => "customers#edit", as: :edit_customer
  get "/customer/edit" => "customers#customer_edit", as: :customer_edit_customer
  post "/customer/update" => "customers#update", as: :update_customer
  post "/customer/customer_update" => "customers#customer_update", as: :customer_update_customer
  get "/customer/update" => "customers#list"
  get "/customer/disable/:customer_id" => "customers#disable", as: :disable_customer
  get "/customer/enable/:customer_id" => "customers#enable", as: :enable_customer
  get "/customer/sign_in" => "customers#new_session", as: :customer_login
  delete "/customer/sign_out" => "customers#delete_session", as: :customer_sign_out
  post "/customer/session/create" => "customers#create_session", as: :create_customer_session
  get "/customer/profile/custom_fields" => "customer_profiles#get_column_header"

  get "/administrator/edit" => "users#edit", as: :edit_admin_profile
  post "/administrator/update" => "users#update", as: :update_admin_profile
  get "/administrator/update" => "users#edit"

  get "/customer/message/profile" => "customer_profiles#new", as: :customer_message_profile
  post "/customer/message/profile/create" => "customer_profiles#create", as: :customer_create_message_profile
  get "/customer/message/profile/create" => "customer_profiles#new"
  get "/customer/message/profile/finalize/:profile_id" => "customer_profiles#finalize", as: :customer_finalize_message_profile
  post "/customer/message/profile/update" => "customer_profiles#update", as: :customer_update_message_profile
  get "/administrator/message/profile/finalize" => "profiles#finalize", as: :finalize_message_profile
  get "/customer/message/profile/list" => "customer_profiles#list", as: :list_customer_message_profile
  get "/customer/message/profile/enable/:profile_id" => "customer_profiles#enable", as: :customer_enable_profile
  get "/customer/message/profile/disable/:profile_id" => "customer_profiles#disable", as: :customer_disable_profile
  get "/customer/email/profile" => "customer_profiles#new_email", as: :customer_email_profile
  post "/customer/email/profile/create" => "customer_profiles#create_email", as: :customer_create_email_profile
  get "/customer/email/profile/create" => "customer_profiles#new_email"
  get "/customer/email/profile/finalize/:profile_id" => "customer_profiles#finalize_email", as: :customer_finalize_email_profile
  get "/customer/email/profile/list" => "customer_profiles#list_email", as: :list_customer_email_profile
  get "/customer/email/profile/enable/:profile_id" => "customer_profiles#email_enable", as: :customer_enable_email_profile
  get "/customer/email/profile/disable/:profile_id" => "customer_profiles#email_disable", as: :customer_disable_email_profile
  post "/customer/email/profile/update" => "customer_profiles#update_email", as: :customer_update_email_profile

  get "/administrator/email/profile" => "profiles#new_email", as: :administrator_email_profile
  post "/administrator/email/profile/create" => "profiles#create_email", as: :administrator_create_email_profile
  get "/administrator/email/profile/create" => "profiles#new_email"
  get "/administrator/email/profile/finalize/:profile_id" => "profiles#finalize_email", as: :administrator_finalize_email_profile
  get "/administrator/email/profile/list" => "profiles#list_email", as: :list_administrator_email_profile
  get "/administrator/email/profile/enable/:profile_id" => "profiles#email_enable", as: :administrator_enable_email_profile
  get "/administrator/email/profile/disable/:profile_id" => "profiles#email_disable", as: :administrator_disable_email_profile
  post "/administrator/email/profile/update" => "profiles#update_email", as: :administrator_update_email_profile

  get "/administrator/message/profile" => "profiles#new", as: :administrator_message_profile
  post "/administrator/message/profile/create" => "profiles#create", as: :administrator_create_message_profile
  get "/administrator/message/profile/finalize/:profile_id" => "profiles#finalize", as: :administrator_finalize_message_profile
  post "/administrator/message/profile/update" => "profiles#update", as: :administrator_update_message_profile
  get "/administrator/message/profile/list" => "profiles#list", as: :list_administrator_message_profile
  get "/administrator/message/profile/enable/:profile_id" => "profiles#enable", as: :administrator_enable_profile
  get "/administrator/message/profile/disable/:profile_id" => "profiles#disable", as: :administrator_disable_profile

  get '/customer/email' => 'customer_emails#new', as: :customer_email
  post '/customer/email/send' => 'customer_emails#send_message', as: :customer_send_email

  get '/administrator/email' => 'administrator_email#new', as: :administrator_email
  post '/administrator/email/send' => 'administrator_email#send_message', as: :administrator_send_email
  get "/administrator/profile/custom_fields" => "profiles#get_column_header"

  get '*rogue_url', :to => 'errors#routing'
  post '*rogue_url', :to => 'errors#routing'
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  include MessagesHelper

  prepend_before_filter :authenticate_user!

  layout "administrator"

  def index
    init_search_form
  end

  def perform
    init_search_form
    init_messages

    @msisdn = params[:msisdn]
    @begin_date = Date.parse(params[:begin_date]) rescue nil
    @end_date = Date.parse(params[:end_date]) rescue nil

    @error = false

    validate_search_params

    set_query_params

    @error_message = messages!(@error_message, "error")

    if @error
      render :index
    else
      render :perform
    end
  end

  def init_search_form
    @search_active = true
  end

  def validate_search_params
    if @msisdn.blank? && @begin_date.blank? && @end_date.blank?
      @error = true
      @error_message << "Veuillez entrer au moins un terme de recherche.<br />"
    end
  end

  def set_query_params
    message_logs_query = ""
    transaction_logs_query = ""
    if !@msisdn.blank?
      message_logs_query << "msisdn LIKE '%#{@msisdn.strip}%'"
      if !@begin_date.blank? and !@end_date.blank?
        message_logs_query << " AND created_at BETWEEN '#{@begin_date}' AND '#{@end_date}'"
      else
        if !@begin_date.blank?
          message_logs_query << " AND created_at > '#{@begin_date}'"
        end
        if !@end_date.blank?
          message_logs_query << " AND created_at < '#{@end_date}'"
        end
      end
      @message_logs = MessageLog.where(message_logs_query + " AND user_id = #{current_user.id}")
      @message_logs_count = @message_logs.count
      @message_logs = @message_logs.page(params[:page])
    else
      if !@begin_date.blank? and !@end_date.blank?
        transaction_logs_query << "created_at BETWEEN '#{@begin_date}' AND '#{@end_date}'"
      else
        if !@begin_date.blank?
          message_logs_query << " AND created_at > '#{@begin_date}'"
        end
        if !@end_date.blank?
          message_logs_query << " AND created_at < '#{@end_date}'"
        end
      end
      @transaction_logs = SmsTransaction.where(transaction_logs_query + " AND user_id = #{current_user.id}")
      @transaction_logs_count = @transaction_logs.count
      @transaction_logs = @transaction_logs.page(params[:page])
    end

    if @message_logs.blank? && @transaction_logs.blank?
      @error = true
      @error_message << "Aucun résultat n'a été trouvé.<br />"
    end
  end

  def init_messages
    @error_message = ""
    @success_message = ""
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/index.html.erb
<!-- Title area -->
<div class="titleArea">
    <div class="wrapper">
        <div class="pageTitle">
            <h5>Recherches</h5>
            <span>Interface de recherche d'abonnés et de transactions</span>
        </div>

        <div class="clear"></div>
    </div>
</div>

<div class="line"></div>

<%= render "search/shared/sub_menu" %>

<div class="line"></div>

<!-- Main content wrapper -->
<div class="wrapper">
  <div class="nNote nInformation hideit">
    <p>
      <strong>Renseignez un numéro pour avoir la liste des messages envoyés à ce numéro.</strong><br />
      <strong>Renseignez une période pour avoir la liste des transactions envoyées durant cette période.</strong><br />
      <strong>Renseignez un numéro et une période pour avoir la liste des messages envoyés à ce numéro durant cette période.</strong>
    </p>
  </div>

  <%= @error_message %>
  <%= @success_message %>

  <%= form_tag perform_search_path, method: :post do %>

    <div class="widget">
      <div class="title"><img src="<%= asset_path 'icons/dark/users.png' %>" alt="" class="titleIcon" /><h6>Formulaire de recherche</h6></div>

        <div class="formRow">
          <%= label_tag(:msisdn, "MSISDN") %>
          <div class="formRight">
            <%= text_field_tag "msisdn", (params[:msisdn] rescue nil), placeholder: "Veuillez entrer un numéro de téléphone" %>
          </div>
          <div class="clear"></div>
        </div>
        <div class="formRow">
          <%= label_tag(:begin_date, "Date de début") %>
          <div class="formRight">
              <input type="text" class="datepicker"name = "begin_date" />
          </div>
          <div class="clear"></div>
        </div>
        <div class="formRow">
          <%= label_tag(:end_date, "Date de fin") %>
          <div class="formRight">
              <input type="text" class="datepicker"name = "end_date" />
          </div>
          <div class="clear"></div>
        </div>

        <div class="formRow">
          <%= submit_tag 'Rechercher', class: 'basic' %>
        </div>
    </div>

  <% end %>


</div>
<!-- End Main content wrapper -->

app/views/search/perform.html.erb
<!-- Title area -->
<div class="titleArea">
    <div class="wrapper">
        <div class="pageTitle">
          <h5>Termes de recherche:</h5>
          <span>Numéro: <b><%= @msisdn %></b></span><br />
          <span>Date de début: <b><%= @begin_date %></b></span><br />
          <span>Date de fin: <b><%= @end_date %></b></span><br />
          <% if @message_logs_count %>
            <span>Nombre de messages: <b><%= @message_logs_count %></b></span>
          <% else %>
            <span>Nombre de transactions: <b><%= @transaction_logs_count %></b></span>
          <% end %>
        </div>

        <div class="clear"></div>
    </div>
</div>

<div class="line"></div>

<%= render "search/shared/sub_menu" %>

<div class="line"></div>

<!-- Main content wrapper -->
<div class="wrapper">
  <div class="nNote nInformation hideit">
    <p>
      <strong>1701: </strong>Succès de l'envoi.<br />
      <strong>1702: </strong>URL invalide.<br />
      <strong>1703: </strong>Combinaison login/mot de passe invalide.<br />
      <strong>1704: </strong>Type de message invalide.<br />
      <strong>1705: </strong>Message invalide.<br />
      <strong>1706: </strong>Numéro du destinataire invalide.<br />
      <strong>1707: </strong>Emetteur du message non valide.<br />
      <strong>1710: </strong>Erreur interne.<br />
      <strong>1025: </strong>Crédit insuffisant.<br />
      <strong>1715: </strong>Erreur de timeout.<br />
  </div>
  <div class="widget">
    <% if !@message_logs.blank? %>
      <div class="title"><img src="<%= asset_path 'icons/dark/full2.png' %>" alt="" class="titleIcon" /><h6>Liste des messages</h6></div>
      <table cellpadding="0" cellspacing="0" border="0" class="sTable taskWidget" width = "100%">

        <%= render "search/shared/message_logs_list", message_logs: @message_logs %>

        <tfoot>
          <tr>
            <td colspan="8">
              <div class="tPagination">
                <%= paginate @message_logs, :params => {:controller => :search, :action => :perform} %>
              </div>
            </td>
          </tr>
        </tfoot>
      </table>
    </div>
  <% else %>
    <div class="title"><img src="<%= asset_path 'icons/dark/full2.png' %>" alt="" class="titleIcon" /><h6>Liste des transactions</h6></div>
      <table cellpadding="0" cellspacing="0" border="0" class="sTable taskWidget" width = "100%">

        <%= render "search/shared/transactions_list", transactions: @transaction_logs %>

        <tfoot>
          <tr>
            <td colspan="8">
              <div class="tPagination">
                <%= paginate @transaction_logs, :params => {:controller => :search, :action => :perform} %>
              </div>
            </td>
          </tr>
        </tfoot>
      </table>
    </div>
  <% end %>

</div>
<!-- End Main content wrapper -->